# Spring配置
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.53.112.43:3306/panorama?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: aLo:ZkJf{6@4
  data:
    redis:
      host: 106.53.112.43
      # Redis 服务端口
      port: 6379
      # 数据库索引
      database: 1
      # 连接超时时间
      timeout: 60s
      # Redis 密码（如果需要）
      password: 7AB2V$|-=uT%
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 1
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池的最大数据库连接数
          max-active: 20
          # 连接池最大阻塞等待时间
          max-wait: -1ms
      client-type: lettuce
