# Server配置
server:
  port: 9000
  servlet:
    context-path: /panorama

# Spring配置
spring:
  application:
    name: panoramic-sample
  profiles:
    active: dev
  jackson:
    mapper:
      sort-properties-alphabetically: false
